### ISSUE TITLE
`Object.instance_methods.include?('tap')` is always false (looks for string in symbol array)

### ISSUE THREAD

**Issue by bughit** [raganwald/andand#10]
``` ruby
    unless Object.method_defined?('tap')
      alias :tap :me
    end
```

**Comment by codener** [comment]
This issue hit me bad today, as `andand`s `#tap` implementation does not work in one scenario, whereas `Kernel#tap` works as it should.

In my scenario, `Page.last.tap(&:save)` (simplified example from Rails) failed with 

```plain
/home/dominik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/andand-1.3.3/lib/andand.rb:66: [BUG] Stack consistency error (sp: 186, bp: 185)
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

and sheets of stacktraces following.

**Comment by codener** [comment]
If you'll merge it, I'll be happy to prepare a pull request.

**Comment by codener** [comment]
Thank you very much!
