### ISSUE TITLE
Question: Any successor of ick?

### ISSUE THREAD

**Issue by dumblob** [raganwald/andand#13]
Hi @raganwald, after my first few steps into the "monadic" world, I found this repository and thanks to it also [Ick](https://github.com/raganwald-deprecated/ick ). Unfortunately I could not find any maintained version of Ick. Do you know about any developed version of Ick or it's successor?

**Comment by raganwald** [comment]
Alas, no, this Ick was an experiment on my part.

**Comment by dumblob** [comment]
It was a really interesting idea, thanks!
